services:
  db:
    env_file: ./backend/.env
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: quicksketch
    ports:
      - "5432:5432"
    volumes:
      - ./backend/src/sql/db.sql:/docker-entrypoint-initdb.d/01-db.sql:ro
      - ./backend/src/sql/demodata.sql:/docker-entrypoint-initdb.d/02-demodata.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d quicksketch"]
      interval: 5s
      timeout: 5s
      retries: 10
      
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PW}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - JWT_KEY=${JWT_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
